import React,{useState} from 'react'
import { useNavigate } from 'react-router-dom'
import { logo, preview } from '../assets'
import {getRendomPrompt} from '../utils'
import { FromFiled,Loader } from '../Componant'


const CreatePost = () => {
  const navigate = useNavigate()
  const [from, setFrom] = useState({
    name:"",
    prompt:"",
    photo:""
  })
  const [generatingImg, setGeneratingImg] = useState(false)
  const [loading, setloading] = useState(false);

  
  const generateImage = async () => {
    if (from.prompt) {
      try {
        setGeneratingImg(true);
        const response = await fetch('http://localhost:8080/api/v1/dalle', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            prompt: from.prompt,
          }),
        });

        const data = await response.json();
        setFrom({ ...from, photo: `data:image/jpeg;base64,${data.photo}` });
      } catch (err) {
        alert(err);
      } finally {
        setGeneratingImg(false);
      }
    } else {
      alert('Please provide proper prompt');
    }
  };



  const handleSubmit= async()=>{
    e.preventDefault();
    if(from.prompt && from.photo){
      setloading(true);
      try {
        const response = await fetch('http://localhost:8080/api/v1/post',{
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(from)
        })
        await response.json();
        //go back to home to see our post image using navigate
        navigate('/');
      } catch (error) {
        alert(error)
        setloading(false);
      }
    }else{
      alert('please enter a prompt and generate an image')
    }
  }
  const handleChange=(e)=>{
    setFrom({...from, [e.target.name]:e.target.value})
  }

  const  handleSurpriseMe =()=>{
    const randomprompt = getRendomPrompt(from.prompt);
    setFrom({...from, prompt:randomprompt})
  }

  return (
    <section className='max-w-7xl max-auto'>
     <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>Create</h1>
      <p className='mt-2 text-[#666e75] text-[16px] max-w [500px]'>Create imaginative and visual stunning images generated by DELL-E AI and share  them with community</p>
      </div>
      <form className="mt-16 max-w-3xl" onSubmit={handleSubmit}>
          <div className='flex flex-col gap-5'>
            <FromFiled 
            labelName="Your name"
            type="text"
            name="name"
            placeholder="Nayan of your Heart"
            value={from.name}
            handleChange={handleChange}
            />
            <FromFiled 
            labelName="prompt"
            type="text"
            name="prompt"
            placeholder="a plush toy robot sitting against yeall wall"
            value={from.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={ handleSurpriseMe}/>
            <div className='relative bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
              {from.photo?(
                <img src={from.photo}
                alt={from.photo}
                className='w-full h-full object-contain'
                />
              ):(
                <img src={preview} alt="preview" className='w-9/12 object-contain opacity-40' 
                />
              )}
              {generatingImg && (
                <div className='absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg'>
                  <Loader/>
                </div>
              )}
        </div>
      </div>
      <div className='mt-5 flex gap-5'>
        <button
        type='button'
         onClick={generateImage}
         className='text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'
        >
          {generatingImg? 'Generating...' : 'Generate'}
        </button>
      </div>
      <div className='mt-10' >
           <p className='mt-2 text-[#666e75]text-[14px]'>Once you have crated the image you want, you can share it with other in the community </p>
           <button
           type='submit'
           className='mt-3 text-white bg-[#6469ff] font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'
           >
            {loading? 'Sharing...' : 'Share With The Community'}
           </button>
      </div>
      </form>
    </section> 
  )
}


export default CreatePost


